apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh","-c"]
    args:
      - while true; do date >> /shared/log.txt; sleep 5; done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared

  - name: reader
    image: busybox
    command: ["/bin/sh","-c"]
    args:
      - while true; do cat /shared/log.txt; sleep 10; done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared

  volumes:
  - name: shared-volume
    emptyDir: {}
