apiVersion: v1
kind: Pod
metadata:
  name: multi-volume-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh","-c","sleep 3600"]

    volumeMounts:
    - mountPath: /tmp/cache
      name: cache-vol

    - mountPath: /data
      name: data-vol

    - mountPath: /etc/config
      name: config-vol

  volumes:
  - name: cache-vol
    emptyDir:
      medium: Memory

  - name: data-vol
    persistentVolumeClaim:
      claimName: app-pvc

  - name: config-vol
    configMap:
      name: app-config
